### ISSUE TITLE
melpa-stable

### ISSUE THREAD

**Issue by rocha** [rdallasgray/pallet#29]
I love pallet. Any chance of getting it into `melpa-stable`?

**Comment by rocha** [comment]
It seems however that some of the pallet dependencies are not on melpa-stable, which forcing using the original melpa, which causes all package to ignore melpa-stable.

I get errors when using only melpa-stable.

**Comment by DarwinAwardWinner** [comment]
@milkypostman, how does melpa-stable handle packages with tagged stable releases that depend on ones without?

**Comment by milkypostman** [comment]
We don't currently have a way to handle this. Our main goal right now is to just get those packages updated to stable (see: milkypostman/melpa#1955)
