### ISSUE TITLE
Support for paradox

### ISSUE THREAD

**Issue by Trevoke** [rdallasgray/pallet#45]
There's a package that improves upon the built-in package list:

https://github.com/Bruce-Connor/paradox

It would be cool if Pallet supported that and it updated the Cask file when changes get made through there.

**Comment by rdallasgray** [comment]
Yeah, I'm aware of Paradox. to my understanding it uses `package-install` and `package-delete` under the hood, so it should work transparently with Pallet. Does it not?

**Comment by Trevoke** [comment]
Well, that's my bad. I didn't read the documentation for pallet 0.7 so I didn't expect the breaking change; I should have known better since it's pre-1.0 :)

Please accept my apologies.

**Comment by rdallasgray** [comment]
No problem - sorry for the inconvenience!

**Comment by rjww** [comment]
Just tried Paradox alongside Pallet, and as far as I can tell Pallet isn't catching its `package-install` calls. I'm on a fresh `--HEAD` install in OS X, so not sure if it's also the case on 24.

**Comment by rjww** [comment]
Looks like it's only a problem if `paradox-execute-asynchronously` is set to `t`.

**Comment by gafalcon** [comment]
Im also having problems with Cask file not updating when I install packages asynchronously with paradox. Any ideas on how to fix this?
Thanks in advance.
