### ISSUE TITLE
Error using Melpa stable

### ISSUE THREAD

**Issue by nlamirault** [rdallasgray/pallet#48]
I can't install your package using only Melpa stable : 

```bash
Dependency pallet failed to install: Package `package-build-0.1' is unavailable
```

It seems comes from Cask ? [1]

[1] : https://github.com/cask/cask/issues/282

**Comment by rdallasgray** [comment]
See https://github.com/rdallasgray/pallet/issues/29 -- this is an issue with Melpa Stable. I'll remove the badge from the README as it implies that Pallet can be properly installed from Melpa Stable, which it can't at present. I don't have control over whether Pallet is available from Melpa Stable or not, other than to stop tagging releases (I think).

**Comment by rdallasgray** [comment]
https://github.com/rdallasgray/pallet/commit/6b3d71c7908731458191cdb7ccd3c0f7f390bc0d

**Comment by rocha** [comment]
With the latest version of pallet, which supports VC references, you can do:

```
(source melpa-stable)

(depends-on "package-build" :git "https://github.com/milkypostman/melpa" :files ("package-build.el"))
(depends "pallet")
```
